### ISSUE TITLE
Warning if there is no featured image

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-schema#12]
Noticed this in my posts archive when a post didn't have an image.

Warning: getimagesize(): Filename cannot be empty in /home/dreamwhi/public_html/dev8/wp-content/plugins/genesis-simple-schema/includes/views/entry-publisher-object.php on line 2

**Comment by dreamwhisper** [comment]
I don't appear to have access here to label or add labels.

**Comment by dreamwhisper** [comment]
@nathanrice I'm still getting this warning. Verified the file change is on my server.

**Comment by dreamwhisper** [comment]
@nathanrice I mis-reported this error. It is actually caused by https://github.com/copyblogger/genesis-simple-schema/blob/develop/includes/views/entry-publisher-object.php#L2

**Comment by nathanrice** [comment]
Should be fixed now.

**Comment by dreamwhisper** [comment]
@nathanrice That worked. I'm not able to label here though. I'll close this, just need to make sure it gets updated for actual site testing.
