### ISSUE TITLE
Organization: A value for the logo field is required.

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-schema#14]
With the following settings, Google reports "A value for the logo field is required." in https://search.google.com/structured-data/testing-tool/

![missing-logo](https://cloud.githubusercontent.com/assets/1271053/21483990/49b23b98-cb59-11e6-9d03-2ff45b5c3c90.PNG)

This error also occurs with Article selected as the Schema type. It does not occur with CreativeWork selected.

Obviously, we're using an image there and it is output on the front end, but Google doesn't see the logo as being included. `logo` is required according to their docs.

This is the full suggested markup they provide:
```html
<div itemscope itemtype="http://schema.org/NewsArticle">
  <meta itemscope itemprop="mainEntityOfPage"  itemType="https://schema.org/WebPage" itemid="https://google.com/article"/>
  <h2 itemprop="headline">Article headline</h2>
  <h3 itemprop="author" itemscope itemtype="https://schema.org/Person">
    By <span itemprop="name">John Doe</span>
  </h3>
  <span itemprop="description">A most wonderful article</span>
  <div itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
    <img src="https://google.com/thumbnail1.jpg"/>
    <meta itemprop="url" content="https://google.com/thumbnail1.jpg">
    <meta itemprop="width" content="800">
    <meta itemprop="height" content="800">
  </div>
  <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
    <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
      <img src="https://google.com/logo.jpg"/>
      <meta itemprop="url" content="https://google.com/logo.jpg">
      <meta itemprop="width" content="600">
      <meta itemprop="height" content="60">
    </div>
    <meta itemprop="name" content="Google">
  </div>
  <meta itemprop="datePublished" content="2015-02-05T08:00:00+08:00"/>
  <meta itemprop="dateModified" content="2015-02-05T09:20:00+08:00"/>
</div>
```

Publisher:
```html
  <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
    <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
      <img src="https://google.com/logo.jpg"/>
      <meta itemprop="url" content="https://google.com/logo.jpg">
      <meta itemprop="width" content="600">
      <meta itemprop="height" content="60">
    </div>
    <meta itemprop="name" content="Google">
  </div>
````

We have `itemprop="image".` Theirs is `itemprop="logo"`.
```html
<div itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
<h2 itemprop="name">Organization Test</h2>
<p itemprop="description">
<span itemprop="image" itemscope="" itemtype="http://schema.org/ImageObject">
<img src="http://dev8.dreamwhisperdesigns.com/wp-content/uploads/2015/10/cropped-logo290.png" class="alignleft">
<meta itemprop="url" content="http://dev8.dreamwhisperdesigns.com/wp-content/uploads/2015/10/cropped-logo290.png">
<meta itemprop="width" content="600">
<meta itemprop="height" content="186">
</span>
this is a description</p>
</div>
```

**Comment by dreamwhisper** [comment]
Note: testing matrix at https://docs.google.com/a/copyblogger.com/spreadsheets/d/13kdNxRdS-N9Nzd9fw987rBsGuBnPpvT5i9Ql03FFooA/edit?usp=sharing

**Comment by cjkoepke** [comment]
This is related to #15, but can't test till right values output the schema markup for an image.

**Comment by nathanrice** [comment]
Should be able to test now. The logic should prevent the schema from outputting unless a URL is entered into the image field, though there's no way to really test the validity of the image, so we're trusting users not to be idiots ... and if they are, it's their own fault.

**Comment by cjkoepke** [comment]
@nathanrice Hmm, I have this for the backend:

<img width="720" alt="screen shot 2017-01-30 at 1 49 16 pm" src="https://cloud.githubusercontent.com/assets/2815568/22441077/1b2ada86-e6f3-11e6-98db-b153c9f1de0f.png">


But still not getting any image output.

**Comment by dreamwhisper** [comment]
> The logic should prevent the schema from outputting unless a URL is entered into the image field

That appears to be working correctly. I tested BlogPosting, Article, and Creative Work and get no errors in the testing tool if an image is included.

Obviously, you'll get an error if you select BlogPosting or Article if nothing is output. We just need to make it clear in docs and possibly revisit this for enhancement with tooltips at a later date.

**Comment by dreamwhisper** [comment]
cc @copyblogger/documentation
