### ISSUE TITLE
Warnings if Publisher logo/url incorrect

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-schema#15]
If you mistakenly copy and paste text into the logo url field, you get these warnings on the front end (debug on).

>Warning: getimagesize(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/dreamwhi/public_html/dev8/wp-content/plugins/genesis-simple-schema/includes/views/entry-publisher-object.php on line 8

>Warning: getimagesize(http://A%20value%20for%20the%20publisher%20field%20is%20required.): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/dreamwhi/public_html/dev8/wp-content/plugins/genesis-simple-schema/includes/views/entry-publisher-object.php on line 8

Along with broken image output.
![broken](https://cloud.githubusercontent.com/assets/1271053/21484642/3159b2fa-cb64-11e6-9d19-8f8d59b94dba.png)

We should be validating that it is a URL at minimum. 

Ideally, we'd hook this into the media uploader.

![edit post jennifer s long stupid title for a site wordpress](https://cloud.githubusercontent.com/assets/1271053/21484970/94f9adc4-cb69-11e6-8666-d29c31c8355c.png)

**Comment by cjkoepke** [comment]
@dreamwhisper Tested this and it appears to be validating the URL field correctly. Added this on the backend:

<img width="937" alt="screen shot 2017-01-30 at 1 02 18 pm" src="https://cloud.githubusercontent.com/assets/2815568/22439352/83c9abbe-e6ec-11e6-89ca-5db42202485b.png">

And it's outputting this on the frontend:

<img width="687" alt="screen shot 2017-01-30 at 1 03 47 pm" src="https://cloud.githubusercontent.com/assets/2815568/22439365/9105fcf6-e6ec-11e6-8428-12ca59feabbc.png">

**Comment by dreamwhisper** [comment]
I get no warnings on my dev any longer. @cjkoepke does a regular image output though?

**Comment by cjkoepke** [comment]
@dreamwhisper @nathanrice Just posted an working URL and it appears that the whole block doesn't output at the bottom of the post. Not sure what the intended result should be, but that doesn't seem right.

The article does get updated with the right schema type, however: 

<img width="268" alt="screen shot 2017-01-30 at 1 16 32 pm" src="https://cloud.githubusercontent.com/assets/2815568/22439831/5c8a9624-e6ee-11e6-80f2-6f8411bd9046.png">

**Comment by dreamwhisper** [comment]
Yep, I got the same result.

**Comment by nathanrice** [comment]
Should be fixed now.

**Comment by dreamwhisper** [comment]
@nathanrice I have output now, but now we're back to the same errors in https://github.com/copyblogger/genesis-simple-schema/issues/15#issue-197605636

**Comment by dreamwhisper** [comment]
Working now with the last commit: https://github.com/copyblogger/genesis-simple-schema/commit/c38dcee0dbbf417301a0f5053f7f3c094082321f

Calling this one confirmed and closing.
